---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/version: v0.23.1
    app.kubernetes.io/part-of: thanos
spec:
  ports:
  - name: http
    port: 10913
    protocol: TCP
    targetPort: 10913
  selector:
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/part-of: thanos
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend-external
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/version: v0.23.1
    app.kubernetes.io/part-of: thanos
spec:
  ports:
  - name: http
    port: 10913
    protocol: TCP
    targetPort: 10913
    nodePort: 30913
  selector:
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/part-of: thanos
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/version: v0.23.1
    app.kubernetes.io/part-of: thanos
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-query-frontend
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/part-of: thanos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-query-frontend
        app.kubernetes.io/component: query-frontend
        app.kubernetes.io/part-of: thanos
    spec:
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - thanos-query-frontend
              - key: app.kubernetes.io/component
                operator: In
                values:
                - query-frontend
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - thanos-query-frontend
              - key: app.kubernetes.io/component
                operator: In
                values:
                - query-frontend
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: thanos-query-frontend
        image: registry.cn-shanghai.aliyuncs.com/hybfkuf/thanos:v0.23.1
        args: 
        - query-frontend
        - --log.level=info
        - --log.format=logfmt
        - --query-frontend.compress-responses
        - --http-address=0.0.0.0:10913
        - --query-frontend.downstream-url=http://thanos-query.monitoring.svc.cluster.local.:10904
        - --query-range.split-interval=12h
        - --labels.split-interval=12h
        - --query-range.max-retries-per-request=10
        - --labels.max-retries-per-request=10
        - --query-frontend.log-queries-longer-than=10s
        ports:
        - name: http
          containerPort: 10913
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10913
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10913
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        terminationMessagePolicy: FallbackToLogsOnError
