#kubectl edit prometheus k8s
 
  # 有了 thanos 已经不需要多个 prometheus 了
  replicas: 1
  # 一定要 externalLabels，否则就会有 metrics 重复，导致 thanos 和 prometheus remote write 出错
  # https://issueexplorer.com/issue/thanos-io/thanos/4767
  externalLabels:
    cluster: cicd

  remoteWrite:
  - name: thanos-receive
    url: http://thanos-receive.monitoring.svc.cluster.local:10908/api/v1/receive
    #sendExemplars: false

  remoteWrite:
  - name: thanos-receive
    url: http://10.240.2.10:30908/api/v1/receive
    #sendExemplars: false
