#kubectl edit prometheus k8s
 
  # 有了 thanos 已经不需要多个 prometheus 了
  # alertmanager 还是需要多个，一般是 3 个
  replicas: 1
  # 一定要 externalLabels，否则就会有 metrics 重复，导致 thanos 和 prometheus remote write 出错
  # https://issueexplorer.com/issue/thanos-io/thanos/4767
  externalLabels:
    cluster: "<cluster_name>"

  # thanos 如果部署在当前 k8s 集群，url 指向内部 thanos 的 service
  remoteWrite:
  - name: thanos-receive
    url: http://thanos-receive.monitoring.svc.cluster.local:10908/api/v1/receive
    #sendExemplars: false

  # thanos 如果不是部署在当前 k8s 集群，url 指向外部 thanos 的 nodePort
  remoteWrite:
  - name: thanos-receive
    url: http://10.240.2.10:30908/api/v1/receive  
    #sendExemplars: false   
