apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thanos-tools
  namespace: monitoring
  labels:
    app.kubernetes.io/name: thanos-tools
    app.kubernetes.io/part-of: thanos
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/auth-type: basic
    #nginx.ingress.kubernetes.io/auth-secret: thanos-basic-auth         # Username: thanos, Password: thanos
    #nginx.ingress.kubernetes.io/auth-realm: 'Thanos Authentication'
spec:
  ingressClassName: nginx
  rules:
  - host: thanos-tools.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thanos-tools
            port:
              number: 10914
